CREATE TABLE time
(
    start_time TIMESTAMP NOT NULL DISTKEY SORTKEY PRIMARY KEY,
    hour INTEGER NOT NULL,
    day INTEGER NOT NULL,
    week INTEGER NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    weekday VARCHAR NOT NULL
)