CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_MOVIES(
	ADULT BOOLEAN,
	BELONGS_TO_COLLECTION VARCHAR(2048),
	BUDGET INT4,
	GENRES VARCHAR(4096),
	HOMEPAGE VARCHAR(1024),
	MOVIE_ID INT4 NOT NULL,
	IMDB_ID VARCHAR(16) NOT NULL,
	ORIGINAL_LANGUAGE VARCHAR(8),
	ORIGINAL_TITLE VARCHAR(1024),
	OVERVIEW VARCHAR(4096),
	POPULARITY REAL,
	POSTER_PATH VARCHAR(1024),
	PRODUCTION_COMPANIES VARCHAR(2048),
	PRODUCTION_COUNTRIES VARCHAR(2048),
	RELEASE_DATE DATE, 
	REVENUE INT8,
	RUNTIME INT4,
	SPOKEN_LANGUAGES VARCHAR(2048),
	STATUS VARCHAR(32),
	TAGLINE VARCHAR(2048),
	TITLE VARCHAR(1024),
	VIDEO BOOLEAN,
	VOTE_AVERAGE REAL,
	VOTE_COUNT INT4,
	GENRE_IDS VARCHAR(1024),
	PRODUCTION_COMPANIES_IDS VARCHAR(1024),
	PRODUCTION_COUNTRIES_ABBVS VARCHAR(1024),
	SPOKEN_LANGUAGES_ABBVS VARCHAR(1024),
	RELEASE_MONTH INT4,
	RELEASE_YEAR INT4
)
DISTKEY(MOVIE_ID);
 
CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_GENRES(
	MOVIE_ID INT4 NOT NULL,
	GENRE_ID VARCHAR(256),
	NAME VARCHAR(256)
)
DISTKEY(GENRE_ID);
 
CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_PRODUCTION_COMPANIES(
	MOVIE_ID INT4 NOT NULL,
	PRODUCTION_COMPANIES_ID VARCHAR(16),
	NAME VARCHAR(256)
)
DISTKEY(PRODUCTION_COMPANIES_ID);
 
CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_PRODUCTION_COUNTRIES(
	MOVIE_ID INT4 NOT NULL,
	PRODUCTION_COUNTRIES_ABBV VARCHAR(8),
	NAME VARCHAR(256)
)
DISTKEY(PRODUCTION_COUNTRIES_ABBV);
 
CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_SPOKEN_LANGUAGES(
	MOVIE_ID INT4 NOT NULL,
	SPOKEN_LANGUAGES_ABBV VARCHAR(8),
	NAME VARCHAR(256)
)
DISTKEY(SPOKEN_LANGUAGES_ABBV);
 
CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_RATINGS(
	USER_ID INT4 NOT NULL,
	MOVIE_ID INT4 NOT NULL,
	RATING REAL,
	EPOCH_TIME INTEGER NOT NULL,
	RATING_TIME TIMESTAMP NOT NULL,
	RATING_MONTH INT4,
	RATING_YEAR INT4
)
DISTKEY(MOVIE_ID)
SORTKEY(USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES(
	GENRE_ID VARCHAR(16) NOT NULL,
	GENRE_NAME VARCHAR(128),
	CONSTRAINT GENRES_PKEY PRIMARY KEY (GENRE_ID)
)
DISTKEY(GENRE_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCTION_COMPANIES(
	COMPANY_ID VARCHAR(16) NOT NULL,
	COMPANY_NAME VARCHAR(128),
	CONSTRAINT COMPANIES_PKEY PRIMARY KEY (COMPANY_ID)
)
DISTKEY(COMPANY_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCTION_COUNTRIES(
	COUNTRY_ABBV VARCHAR(16) NOT NULL,
	COUNTRY_NAME VARCHAR(128),
	CONSTRAINT COUNTRIES_PKEY PRIMARY KEY (COUNTRY_ABBV)
)
DISTKEY(COUNTRY_ABBV);

CREATE TABLE IF NOT EXISTS PUBLIC.SPOKEN_LANGUAGES(
	LANG_ABBV VARCHAR(16) NOT NULL,
	LANG_NAME VARCHAR(128),
	CONSTRAINT LANGS_PKEY PRIMARY KEY (LANG_ABBV)
)
DISTKEY(LANG_ABBV);

CREATE TABLE IF NOT EXISTS PUBLIC.RELEASE_DATES(
	RELEASE_DATE TIMESTAMP NOT NULL,
	RELEASE_YEAR INT4,
	RELEASE_MONTH INT4,
	RELEASE_DAY INT4,
	RELEASE_WEEK INT4,
	RELEASE_WEEKDAY VARCHAR(256),
	CONSTRAINT RELEASES_PKEY PRIMARY KEY (RELEASE_DATE)
)
DISTKEY(RELEASE_DATE);

CREATE TABLE IF NOT EXISTS PUBLIC.MOVIES(
	MOVIE_ID INT4 NOT NULL,
	IMDB_ID VARCHAR(16) NOT NULL,
	BUDGET INT4,
	ADULT BOOLEAN,
	HOMEPAGE VARCHAR(1024),
	ORIGINAL_LANGUAGE VARCHAR(8),
	ORIGINAL_TITLE VARCHAR(1024),
	TITLE VARCHAR(1024),
	OVERVIEW VARCHAR(4096),
	POPULARITY REAL,
	RUNTIME INT4,
	REVENUE INT8,
	STATUS VARCHAR(32),
	TAGLINE VARCHAR(2048),
	VIDEO BOOLEAN,
	VOTE_AVERAGE REAL,
	VOTE_COUNT INT4,
	CONSTRAINT MOVIES_PKEY PRIMARY KEY (MOVIE_ID)
)
DISTKEY(MOVIE_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.RATING_TIMES(
	RATING_TIME TIMESTAMP NOT NULL,
	RATING_YEAR INT4,
	RATING_MONTH INT4,
	RATING_DAY INT4,
	RATING_HOUR INT4,
	RATING_WEEK INT4,
	RATING_WEEKDAY VARCHAR(256),
	CONSTRAINT RATING_TIMES_PKEY PRIMARY KEY (RATING_TIME)
)
DISTKEY(RATING_TIME);

CREATE TABLE IF NOT EXISTS PUBLIC.RATINGS(
	USER_ID INT4 NOT NULL,
	MOVIE_ID INT4 NOT NULL,
	RATING_TIME TIMESTAMP NOT NULL,
	RATING REAL,
	CONSTRAINT RATINGS_PKEY PRIMARY KEY (USER_ID, MOVIE_ID, RATING_TIME)
)
DISTKEY(MOVIE_ID)
SORTKEY(USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_MOVIE_RATINGS(
	USER_ID INT4 NOT NULL,
	MOVIE_ID INT4 NOT NULL,
	RATING_TIME TIMESTAMP NOT NULL,
	RELEASE_DATE DATE,
	GENRE_ID_1 VARCHAR(16),
	GENRE_ID_2 VARCHAR(16),
	PROD_COMPANY_ID_1 VARCHAR(16),
	PROD_COMPANY_ID_2 VARCHAR(16),
	PROD_COUNTRY_ABBV_1 VARCHAR(16),
	PROD_COUNTRY_ABBV_2 VARCHAR(16),
	SPOKEN_LANG_ABBV_1 VARCHAR(16),
	SPOKEN_LANG_ABBV_2 VARCHAR(16),
	CONSTRAINT USER_MOVIE_RATINGS_PKEY PRIMARY KEY (USER_ID, MOVIE_ID, RATING_TIME)
)
DISTKEY(MOVIE_ID);